const SET_USER = 'SET_USER'
const LOG_OUT = 'LOG_OUT'
const SIGN_IN = 'SIGN_IN'
const SIGN_UP = 'SIGN_UP'
const SIGN_UP_COMPLETE = 'SIGN_UP_COMPLETE'
const SIGN_IN_COMPLETE = 'SIGN_IN_COMPLETE'
const SET_SIGN_IN_ERROR = 'SET_SIGN_IN_ERROR '
const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR'
const DISABLE_SIGNUP_ERROR = 'DISABLE_SIGNUP_ERROR'
const DISABLE_SIGNIN_ERROR = 'DISABLE_SIGNIN_ERROR'

export const actionTypes = {
    SET_USER,
    LOG_OUT,
    SIGN_IN,
    SIGN_UP,
    SIGN_IN_COMPLETE,
    SIGN_UP_COMPLETE,
    SET_SIGN_IN_ERROR,
    SET_SIGNUP_ERROR,
    DISABLE_SIGNUP_ERROR,
    DISABLE_SIGNIN_ERROR
}