const SET_USER = 'SET_USER'
const LOG_OUT = 'LOG_OUT'
const SIGN_IN = 'SIGN_IN'
const SIGN_UP = 'SIGN_UP'
const SIGN_UP_COMPLETE = 'SIGN_UP_COMPLETE'
const SIGN_IN_COMPLETE = 'SIGN_IN_COMPLETE'
const SET_AUTH_ERROR = 'SET_AUTH_ERROR '
const DISABLE_AUTH_ERROR = 'DISABLE_AUTH_ERROR'
const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD'
const RESET_PASSWORD = 'RESET_PASSWORD'
const REQUEST_RESET_PASSWORD_COMPLETE = 'REQUEST_RESET_PASSWORD_COMPLETE'
const DISABLE_AUTH_MESSAGE = 'DISABLE_AUTH_MESSAGE'
const SET_AUTH_MESSAGE = 'SET_AUTH_MESSAGE'
const RESET_PASSWORD_COMPLETE = 'RESET_PASSWORD_COMPLETE'
const SEND_CONFIRM_EMAIL = 'SEND_CONFIRM_EMAIL'
const SEND_CONFIRM_EMAIL_COMPLETE = 'SEND_CONFIRM_EMAIL_COMPLETE'
const CONFIRM_EMAIL = 'CONFIRM_EMAIL'
const CONFIRM_EMAIL_COMPLETE = 'CONFIRM_EMAIL_COMPLETE'

export const actionTypes = {
    SET_USER,
    LOG_OUT,
    SIGN_IN,
    SIGN_UP,
    SIGN_IN_COMPLETE,
    SIGN_UP_COMPLETE,
    SET_AUTH_ERROR,
    DISABLE_AUTH_ERROR,
    REQUEST_RESET_PASSWORD,
    SEND_CONFIRM_EMAIL,
    SEND_CONFIRM_EMAIL_COMPLETE,
    RESET_PASSWORD,
    REQUEST_RESET_PASSWORD_COMPLETE,
    DISABLE_AUTH_MESSAGE,
    SET_AUTH_MESSAGE,
    RESET_PASSWORD_COMPLETE,
    CONFIRM_EMAIL,
    CONFIRM_EMAIL_COMPLETE
}