const SET_USER = "SET_USER";
const LOG_OUT = "LOG_OUT";
const SIGN_IN = "SIGN_IN";
const SIGN_UP = "SIGN_UP";
const SIGN_UP_COMPLETE = "SIGN_UP_COMPLETE";
const SIGN_IN_COMPLETE = "SIGN_IN_COMPLETE";
const SET_AUTH_ERROR = "SET_AUTH_ERROR ";
const DISABLE_AUTH_ERROR = "DISABLE_AUTH_ERROR";
const REQUEST_RESET_PASSWORD = "REQUEST_RESET_PASSWORD";
const RESET_PASSWORD = "RESET_PASSWORD";
const REQUEST_RESET_PASSWORD_COMPLETE = "REQUEST_RESET_PASSWORD_COMPLETE";
const DISABLE_AUTH_MESSAGE = "DISABLE_AUTH_MESSAGE";
const SET_AUTH_MESSAGE = "SET_AUTH_MESSAGE";
const RESET_PASSWORD_COMPLETE = "RESET_PASSWORD_COMPLETE";
const SEND_CONFIRM_EMAIL = "SEND_CONFIRM_EMAIL";
const SEND_CONFIRM_EMAIL_COMPLETE = "SEND_CONFIRM_EMAIL_COMPLETE";
const CONFIRM_EMAIL = "CONFIRM_EMAIL";
const CONFIRM_EMAIL_COMPLETE = "CONFIRM_EMAIL_COMPLETE";
const SET_IS_FETCHING = "SET_IS_FETCHING";
const DISABLE_IS_FETCHING = "DISABLE_IS_FETCHING";
const GET_SUBJECTS = "GET_SUBJECTS";
const GET_GROUP_BY_ID = "GET_GROUP_BY_ID";
const GET_STUDENTS = "GET_STUDENTS";
const GET_GROUPS = "GET_GROUPS";
const GET_SUBJECT_BY_ID = "GET_SUBJECT_BY_ID";
const GET_LESSONS = "GET_LESSONS";
const GET_LESSON_BY_ID = "GET_LESSON_BY_ID";
const GET_QUIZZES = "GET_QUIZZES";
const GET_QUIZ_BY_ID = "GET_QUIZ_BY_ID";
const GET_QUESTIONS = "GET_QUESTIONS";
const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID";
const GET_OPTIONS = "GET_OPTIONS";
const GET_OPTION_BY_ID = "GET_OPTION_BY_ID";
const SET_MAIN_STREAM = "SET_MAIN_STREAM";
const ADD_VIDEO_PARTICIPANT = "ADD_VIDEO_PARTICIPANT";
const REMOVE_VIDEO_PARTICIPANT = "REMOVE_VIDEO_PARTICIPANT";
const SET_VIDEO_USER = "SET_VIDEO_USER";
const UPDATE_VIDEO_USER = "UPDATE_VIDEO_USER";
const UPDATE_VIDEO_PARTICIPANT = "UPDATE_VIDEO_PARTICIPANT";
const FETCH_VIDEO_CHAT_STATE = "FETCH_VIDEO_CHAT_STATE"
const GET_STUDENT_HOME_CONTENT = "GET_STUDENT_HOME_CONTENT"
const GET_MORE_LESSONS = "GET_MORE_LESSONS"
const SET_ONBOARD = "SET_ONBOARD";
const GET_USER_PROFILE = "GET_USER_PROFILE";
const GET_ASSINGMENTS_BY_LESSON_ID = "GET_ASSINGMENTS_BY_LESSON_ID"
const GET_THEORIES_BY_LESSON_ID = "GET_THEORIES_BY_LESSON_ID"
const GET_ASSIGNMENT_BY_ID = "GET_ASSIGNMENT_BY_ID"
const GET_THEORY_BY_ID = "GET_THEORY_BY_ID"

export const actionTypes = {
  SET_USER,
  LOG_OUT,
  SIGN_IN,
  SIGN_UP,
  SIGN_IN_COMPLETE,
  SIGN_UP_COMPLETE,
  SET_AUTH_ERROR,
  DISABLE_AUTH_ERROR,
  REQUEST_RESET_PASSWORD,
  SEND_CONFIRM_EMAIL,
  SEND_CONFIRM_EMAIL_COMPLETE,
  RESET_PASSWORD,
  REQUEST_RESET_PASSWORD_COMPLETE,
  DISABLE_AUTH_MESSAGE,
  SET_AUTH_MESSAGE,
  RESET_PASSWORD_COMPLETE,
  CONFIRM_EMAIL,
  CONFIRM_EMAIL_COMPLETE,
  SET_IS_FETCHING,
  DISABLE_IS_FETCHING,
  GET_SUBJECTS,
  GET_GROUP_BY_ID,
  GET_STUDENTS,
  GET_GROUPS,
  GET_SUBJECT_BY_ID,
  GET_LESSONS,
  GET_LESSON_BY_ID,
  GET_QUIZZES,
  GET_QUIZ_BY_ID,
  GET_QUESTIONS,
  GET_QUESTION_BY_ID,
  GET_OPTIONS,
  GET_OPTION_BY_ID,
  SET_MAIN_STREAM,
  ADD_VIDEO_PARTICIPANT,
  REMOVE_VIDEO_PARTICIPANT,
  SET_VIDEO_USER,
  UPDATE_VIDEO_USER,
  UPDATE_VIDEO_PARTICIPANT,
  FETCH_VIDEO_CHAT_STATE,
  GET_STUDENT_HOME_CONTENT,
  GET_MORE_LESSONS,
  SET_ONBOARD,
  GET_USER_PROFILE,
  GET_ASSINGMENTS_BY_LESSON_ID,
  GET_THEORIES_BY_LESSON_ID,
  GET_ASSIGNMENT_BY_ID,
  GET_THEORY_BY_ID,
};
